package cliref

import (
	"strings"
	"testing"
)

func TestMarkdownIncludesGeneratedNoticeAndCLIFlags(t *testing.T) {
	markdown := Markdown()
	for _, want := range []string{
		"<!-- Code generated by task docs:generate; DO NOT EDIT. -->",
		"## `bv push [--mode local|remote] [--upload-id ID] [--ttl-seconds N] [--include-hidden] <dir>`",
		"`--include-hidden`",
		"## Exit codes",
	} {
		if !strings.Contains(markdown, want) {
			t.Fatalf("generated markdown missing %q", want)
		}
	}
}

func TestUsageTextComesFromReferenceCommands(t *testing.T) {
	usage := UsageText()
	for _, command := range DefaultReference().Commands {
		if command.Hidden {
			continue
		}
		if !strings.Contains(usage, command.Name) {
			t.Fatalf("usage text missing command %q", command.Name)
		}
	}
}
