package apiref

import (
	"strings"
	"testing"
)

func TestMarkdownIncludesOnlyPublicCLIAPI(t *testing.T) {
	markdown := Markdown()
	for _, want := range []string{
		"<!-- Code generated by task docs:generate; DO NOT EDIT. -->",
		"Auth: `Most endpoints use Authorization: Bearer <butverify installation token>. POST /v1/auth/login uses a GitHub user token and returns the butverify token.`",
		"## `POST /v1/auth/login`",
		"## `POST /v1/sites`",
		"## `GET /v1/sites/{site_id}/files/{file_path}`",
		"Bearer GitHub user token",
	} {
		if !strings.Contains(markdown, want) {
			t.Fatalf("generated API markdown missing %q", want)
		}
	}

	for _, excluded := range []string{
		"/v1/dashboard",
		"/v1/webhooks",
		"/v1/auth/start",
		"/v1/auth/callback",
		"/v1/auth/logout",
		"/v1/status",
		"/v1/billing",
		"/healthz",
	} {
		if strings.Contains(markdown, excluded) {
			t.Fatalf("generated API markdown includes internal-only path %q", excluded)
		}
	}
}

func TestDefaultReferenceIsDeterministic(t *testing.T) {
	ref := DefaultReference()
	if len(ref.Operations) == 0 {
		t.Fatal("expected public API operations")
	}
	methodOrder := map[string]int{"GET": 0, "POST": 1, "PUT": 2, "PATCH": 3, "DELETE": 4}
	for i := 1; i < len(ref.Operations); i++ {
		previous := ref.Operations[i-1]
		current := ref.Operations[i]
		if previous.Path > current.Path {
			t.Fatalf("operations are not sorted: %q before %q", previous.Path, current.Path)
		}
		if previous.Path == current.Path && methodOrder[previous.Method] > methodOrder[current.Method] {
			t.Fatalf("methods are not sorted for %s: %s before %s", current.Path, previous.Method, current.Method)
		}
	}
}
