// Package apiref renders the generated public API reference for docs.
package apiref

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"strings"
)

const DocsPath = "marketing-site/src/content/docs/docs/reference/api.md"

//go:embed public-cli-api-reference.json
var manifestBytes []byte

type Reference struct {
	Title         string      `json:"title"`
	Description   string      `json:"description"`
	GeneratedFrom string      `json:"generated_from"`
	GeneratedBy   string      `json:"generated_by"`
	SourceNote    string      `json:"source_note"`
	BaseURL       string      `json:"base_url"`
	Auth          string      `json:"auth"`
	Operations    []Operation `json:"operations"`
}

type Operation struct {
	Method      string       `json:"method"`
	Path        string       `json:"path"`
	Summary     string       `json:"summary"`
	Stability   string       `json:"stability"`
	Auth        string       `json:"auth"`
	Parameters  []Parameter  `json:"parameters"`
	RequestBody *RequestBody `json:"request_body"`
	Responses   []Response   `json:"responses"`
}

type Parameter struct {
	Name        string `json:"name"`
	In          string `json:"in"`
	Required    bool   `json:"required"`
	Description string `json:"description"`
	Schema      string `json:"schema"`
}

type RequestBody struct {
	Required bool   `json:"required"`
	Schema   string `json:"schema"`
}

type Response struct {
	Status      string `json:"status"`
	Description string `json:"description"`
	Schema      string `json:"schema"`
}

func DefaultReference() Reference {
	var ref Reference
	if err := json.Unmarshal(manifestBytes, &ref); err != nil {
		panic(fmt.Sprintf("decode API reference manifest: %v", err))
	}
	return ref
}

func Markdown() string {
	ref := DefaultReference()
	var b strings.Builder
	b.WriteString("---\n")
	fmt.Fprintf(&b, "title: %s\n", ref.Title)
	fmt.Fprintf(&b, "description: %s\n", ref.Description)
	b.WriteString("---\n\n")
	b.WriteString("<!-- Code generated by task docs:generate; DO NOT EDIT. -->\n\n")
	fmt.Fprintf(&b, "> %s Run `task docs:generate` after changing the public API contract.\n\n", ref.SourceNote)
	fmt.Fprintf(&b, "Base URL: `%s`\n\n", ref.BaseURL)
	fmt.Fprintf(&b, "Auth: `%s`\n\n", ref.Auth)
	for _, operation := range ref.Operations {
		fmt.Fprintf(&b, "## `%s %s`\n\n", operation.Method, operation.Path)
		fmt.Fprintf(&b, "%s\n\n", operation.Summary)
		fmt.Fprintf(&b, "- Stability: `%s`\n", operation.Stability)
		fmt.Fprintf(&b, "- Auth: %s\n", operation.Auth)
		writeParameters(&b, operation.Parameters)
		writeRequestBody(&b, operation.RequestBody)
		writeResponses(&b, operation.Responses)
	}
	return b.String()
}

func writeParameters(b *strings.Builder, parameters []Parameter) {
	if len(parameters) == 0 {
		return
	}
	b.WriteString("\nParameters:\n\n")
	b.WriteString("| name | in | required | schema | description |\n")
	b.WriteString("| ---- | -- | -------- | ------ | ----------- |\n")
	for _, parameter := range parameters {
		fmt.Fprintf(
			b,
			"| `%s` | %s | %s | `%s` | %s |\n",
			escapeTable(parameter.Name),
			escapeTable(parameter.In),
			yesNo(parameter.Required),
			escapeTable(parameter.Schema),
			escapeTable(parameter.Description),
		)
	}
}

func writeRequestBody(b *strings.Builder, body *RequestBody) {
	b.WriteString("\nRequest body:\n\n")
	if body == nil {
		b.WriteString("None.\n")
		return
	}
	fmt.Fprintf(b, "- Schema: `%s`\n", body.Schema)
	fmt.Fprintf(b, "- Required: %s\n", yesNo(body.Required))
}

func writeResponses(b *strings.Builder, responses []Response) {
	b.WriteString("\nResponses:\n\n")
	b.WriteString("| status | schema | description |\n")
	b.WriteString("| ------ | ------ | ----------- |\n")
	for _, response := range responses {
		schema := response.Schema
		if schema == "" {
			schema = "-"
		}
		fmt.Fprintf(
			b,
			"| `%s` | `%s` | %s |\n",
			escapeTable(response.Status),
			escapeTable(schema),
			escapeTable(response.Description),
		)
	}
	b.WriteString("\n")
}

func yesNo(value bool) string {
	if value {
		return "yes"
	}
	return "no"
}

func escapeTable(value string) string {
	return strings.ReplaceAll(value, "|", "\\|")
}
